### ISSUE TITLE
Translation not work

### ISSUE THREAD

**Issue by nicodmf** [Soullivaneuh/IsoCodesValidator#125]
As it, the translation doesn't work on the bundle

**Comment by Soullivaneuh** [comment]
@nicodmf Could you please give me some more details? Environment? Installed packages? Steps to reproduce?

I can't do anything with just a "doesn't work" message, sorry.

**Comment by nicodmf** [comment]
I understand, but at this moment, i didn't have time to be precise. In my memory, the problem was : 

- the translation message doesn't show up
- i should write my own tranlation file and the problem was correct

**Comment by Soullivaneuh** [comment]
@nicodmf Could you please provide:

The `composer show` command result from your project?

The code part using the not working assert?

Thanks.

**Comment by nicodmf** [comment]
beberlei/DoctrineExtensions              v1.0.15           
behat/behat                              v3.3.0            
behat/gherkin                            v4.4.5            
behat/mink                               v1.7.1            
behat/mink-browserkit-driver             v1.3.2            
behat/mink-extension                     v2.2              
behat/mink-goutte-driver                 v1.2.1            
behat/mink-selenium2-driver              v1.3.1            
behat/symfony2-extension                 2.1.1             
behat/transliterator                     v1.2.0            
behatch/contexts                         2.6.1             
cocur/slugify                            v2.5              
composer/ca-bundle                       1.0.7             
container-interop/container-interop      1.2.0             
doctrine/annotations                     v1.4.0            
doctrine/cache                           v1.6.1            
doctrine/collections                     v1.4.0            
doctrine/common                          v2.7.2            
doctrine/data-fixtures                   v1.2.2            
doctrine/dbal                            v2.5.12           
doctrine/doctrine-bundle                 1.6.7             
doctrine/doctrine-cache-bundle           1.3.0             
doctrine/inflector                       v1.1.0            
doctrine/instantiator                    1.0.5             
doctrine/lexer                           v1.0.1            
doctrine/orm                             v2.5.6            
ezsystems/privacy-cookie-bundle          dev-master c967a14
fabpot/goutte                            v3.2.1            
fresh/doctrine-enum-bundle               v5.0.0            
friendsofsymfony/user-bundle             v2.0.0            
fzaninotto/faker                         v1.6.0            
gedmo/doctrine-extensions                v2.4.27           
giggsey/libphonenumber-for-php           8.4.2             
giggsey/locale                           1.3               
guzzlehttp/guzzle                        6.2.3             
guzzlehttp/promises                      v1.3.1            
guzzlehttp/psr7                          1.4.2             
hautelook/alice-bundle                   v1.4.1            
incenteev/composer-parameter-handler     v2.1.2            
instaclick/php-webdriver                 1.4.3             
jdorn/sql-formatter                      v1.2.17           
jms/i18n-routing-bundle                  2.0.0             
jms/metadata                             1.6.0             
justinrainbow/json-schema                1.6.1             
knplabs/knp-menu                         2.2.0             
knplabs/knp-menu-bundle                  2.1.3             
kriswallsmith/assetic                    v1.4.0            
lexik/translation-bundle                 v4.0.2            
monolog/monolog                          1.22.1            
nelmio/alice                             v2.3.1            
ocramius/proxy-manager                   1.0.2             
paragonie/random_compat                  v2.0.10           
psr/cache                                1.0.1             
psr/container                            1.0.0             
psr/http-message                         1.0.1             
psr/log                                  1.0.2             
ronanguilloux/isocodes                   2.1.1             
sensio/distribution-bundle               v5.0.18           
sensio/framework-extra-bundle            v3.0.25           
sensio/generator-bundle                  v3.1.4            
sensiolabs/security-checker              v4.0.4            
simplethings/entity-audit-bundle         v1.0.4            
sllh/iso-codes-validator                 v3.0.0            
sonata-project/admin-bundle              3.16.0            
sonata-project/block-bundle              3.3.2             
sonata-project/cache                     1.0.7             
sonata-project/core-bundle               3.3.0             
sonata-project/datagrid-bundle           2.2.1             
sonata-project/doctrine-orm-admin-bundle 3.1.4             
sonata-project/exporter                  1.7.1             
swiftmailer/swiftmailer                  v5.4.7            
symfony/assetic-bundle                   v2.8.1            
symfony/monolog-bundle                   v3.1.0            
symfony/phpunit-bridge                   v3.2.7            
symfony/polyfill-apcu                    v1.3.0            
symfony/polyfill-intl-icu                v1.3.0            
symfony/polyfill-mbstring                v1.3.0            
symfony/polyfill-php56                   v1.3.0            
symfony/polyfill-php70                   v1.3.0            
symfony/polyfill-util                    v1.3.0            
symfony/security-acl                     v3.0.0            
symfony/swiftmailer-bundle               v2.5.4            
symfony/symfony                          v3.2.7            
true/punycode                            v2.1.1            
twig/extensions                          v1.4.1            
twig/twig                                v1.33.2           
vich/uploader-bundle                     1.4.0             
webfactory/exceptions-bundle             4.3.1             
zendframework/zend-code                  2.6.3             
zendframework/zend-eventmanager          3.1.0           

form type
```php
<?php
//...
class WorkCouncilType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
             //...
            ->add('company_registration_number', null, ['required'=>true])
        ;
    }
```
Resources/config/validation.yml
```yml
AppBundle\Entity\WorkCouncil:
    properties:     
        company_registration_number:
            - SLLH\IsoCodesValidator\Constraints\Siret: ~
```

translation/validators.fr.yml
```yml
This value is not a valid SIRET.: Ce code n'est pas un numéro SIRET valide.
```

**Comment by Soullivaneuh** [comment]
So if I understand right, you are trying to override the translation? And this is what is not working.

**Comment by nicodmf** [comment]
If i don't override translation, the translations doesn't work

**Comment by Soullivaneuh** [comment]
I just tried with the last 3.1.0 version, it's working:

![image](https://user-images.githubusercontent.com/1698357/28783256-164f7e0c-7610-11e7-89a9-19df029c68dc.png)

The issue can't be reproduced and seems to be linked to your env.

Please empty your cache, remove your translations overrides and update to the last version.

If the problem persist and you have more clue to provide, feel free to re-open.
