### ISSUE TITLE
Refactor ZipCode validator

### ISSUE THREAD

**Issue by Soullivaneuh** [Soullivaneuh/IsoCodesValidator#7]
Refactor it if following PR is accepted: https://github.com/ronanguilloux/IsoCodes/pull/38

Maybe BC break. Should be on a new major version (e.g. 2.0)

**Comment by barryvdh** [comment]
You mean https://github.com/ronanguilloux/IsoCodes/pull/38 ;)

**Comment by Soullivaneuh** [comment]
Indeed yes, thanks! :+1:

**Comment by Soullivaneuh** [comment]
Waiting for https://github.com/ronanguilloux/IsoCodes/pull/51

**Comment by Soullivaneuh** [comment]
Try to make it available on a new minor version with deprecated error triggering.
